### ISSUE TITLE
Potential switch to FastLed?

### ISSUE THREAD

**Issue by dwhickox** [Legorobotdude/LED-level#1]
I think you should go with the fast led matrix library because it is much more powerful for people that just want to edit your code for something more technical than this, plus in my personal opinion, it is easier to use and configure.

**Comment by Legorobotdude** [comment]
NeoMatrix has the best support for the Adafruits GFX library which is what I am using. In any case the code is simple enough that porting would be trivial for anyone with the need to do so, especially since Adafruit GFX library ports are available. [https://github.com/Jorgen-VikingGod/FastLED-GFX](https://github.com/Jorgen-VikingGod/FastLED-GFX) . Feel free to fork it and port it yourself if you have the need for a port.
